# Generated by Django 4.0.6 on 2022-07-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('amount_dollar', models.IntegerField()),
                ('amount_run', models.IntegerField()),
                ('deadline', models.DateField()),
            ],
            options={
                'ordering': ('-deadline',),
            },
        ),
    ]
