# Generated by Django 4.0.6 on 2022-07-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_amount_run_order_amount_rub_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(),
        ),
    ]
